version: '3.9'


services:

  discoveryServer:
    image: train/discoveryServer:latest
    container_name: discoveryServer
    ports:
      - "8761:8761"
    networks:
      - ${NETWORK_NAME:-train-network}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}

  gatewayService:
    image: train/gatewayService:latest
    container_name: gatewayService
    ports:
      - "8080:8080"
    depends_on:
      - discoveryServer
    networks:
      - ${NETWORK_NAME:-train-network}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discoveryServer:8761/eureka}

  userService:
    image: train/userService:latest
    container_name: userService
    depends_on:
      - discoveryServer
      # - mysql-user
    networks:
      - ${NETWORK_NAME:-train-network}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discoveryServer:8761/eureka}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}

  trainService:
    image: train/trainService:latest
    container_name: trainService
    depends_on:
      - discoveryServer
      # - mysql-train
    networks:
      - ${NETWORK_NAME:-train-network}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discoveryServer:8761/eureka}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}

  bookingService:
    image: train/bookingService:latest
    container_name: bookingService
    depends_on:
      - discoveryServer
      # - mysql-booking
    networks:
      - ${NETWORK_NAME:-train-network}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discoveryServer:8761/eureka}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}

  paymentService:
    image: train/payment-service:latest
    container_name: payment-service
    depends_on:
      - discoveryServer
      # - mysql-payment
    networks:
      - ${NETWORK_NAME:-train-network}
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://discoveryServer:8761/eureka}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
  # TODO: Uncomment and configure the frontend and MySQL services as needed
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - ${NETWORK_NAME:-train-network}

  # mysql-user:
  #   image: mysql:8.0
  #   container_name: mysql-user
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
  #     - MYSQL_DATABASE=userdb
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - ${NETWORK_NAME:-train-network}

  # mysql-train:
  #   image: mysql:8.0
  #   container_name: mysql-train
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
  #     - MYSQL_DATABASE=traindb
  #   ports:
  #     - "3308:3306"
  #   networks:
  #     - ${NETWORK_NAME:-train-network}

  # mysql-booking:
  #   image: mysql:8.0
  #   container_name: mysql-booking
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
  #     - MYSQL_DATABASE=bookingdb
  #   ports:
  #     - "3309:3306"
  #   networks:
  #     - ${NETWORK_NAME:-train-network}
  
  # mysql-payment:
  #   image: mysql:8.0
  #   container_name: mysql-payment
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-password}
  #     - MYSQL_DATABASE=bookingdb
  #   ports:
  #     - "3310:3306"
  #   networks:
  #     - ${NETWORK_NAME:-train-network}
  

networks:
  train-network:
    driver: bridge